spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///jvs
    username: root
    password: justice@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 23333

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.mczhengyi.jvs.bean

logging:
  level:
    top.mczhengyi.jvs.mapper: debug

swagger:
  base-package: top.mczhengyi.jvs.controller
  enable: true

jvs:
  fileServerUrl: http://192.168.31.1
  redisHost: 127.0.0.1:6379
  redisExpire: 604800
  redisTimeout: 5000
  uploadUrl: http://192.168.52.128/file
